services:
  web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - todo-network
    environment:
      - DB_HOST=db
      - DB_NAME=todolist
      - DB_USER=postgres
      - DB_PASSWORD=postgres

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=todolist
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./export_todo.sql:/docker-entrypoint-initdb.d/export_todo.sql
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge

volumes:
  postgres_data:
