name: PHP Composer

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ${{ secrets.DB_NAME }}
          POSTGRES_USER: ${{ secrets.DB_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASS }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5     
          
    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP environment
      uses: nanasess/setup-php@v4.1.0
      with:
        php-version: '8.2'
        extensions: pdo, pdo_pgsql
    
    - name: Initialize database
      run: |
        psql -h localhost -U ${{secrets.DB_USERNAME}} -d ${{secrets.DB_NAME}} -f db/init.sql
      env:
        PGPASSWORD: postgres
      
    - name: Initialize test database
      run: |
        psql -h localhost -U postgres -d ${{secrets.DB_NAME}} -f db/init.sql
      env:
        PGPASSWORD: ${{ secrets.DB_PASS}}

    - name: Verify database connection
      run: |
        php -r "
          \$dbh = new PDO('pgsql:host=localhost;dbname='${{secrets.DB_NAME}}', '${{secrets.DB_USERNAME}}', '${{secrets.DB_PASS}}');
          echo 'Database connection successful\n';
          \$result = \$dbh->query('SELECT COUNT(*) FROM ${{secrets.DB_NAME}}');
          echo 'Number of tasks: ' . \$result->fetchColumn();
        "
    
    - name: Verify database connection
      run: php backend/test_connexion.php
      env:
        DB_HOST: localhost
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASS }}

    - name: Run test suite
      run: php tests/test.php
      env:
        DB_CONNECTION: pgsql
        DB_HOST: localhost
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASS }}
